[package]
name = "rsmpeg"
version = "0.1.0"
authors = ["liudingming <liudingming@bytedance.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty_ffmpeg = "0.5"
libc = "0.2"
paste = "1.0"
thiserror = "1.0"

[dev-dependencies]
env_logger = "0.8"
log = "0.4"
